OnlineShop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Models
{
    public class Product
    {
        public int Id { get; set; }
        
        [Required]
        public string Name { get; set; }

        [Required]
        [StringLength(20)]
        public string Color { get; set; }

        [Column("CategoryFK")]
        public int CategoryFK { get; set; }

        [ForeignKey("CategoryFK")]
        public virtual Categories Category { get; set; }

        [Column("ManufacturerFK")]
        public int ManufacturerFK { get; set; }

        [ForeignKey("ManufacturerFK")]
        public virtual Manufacturer Manufacturer { get; set; }

        public string Description { get; set; }

        [Required]
        public int Count { get; set; }

        [Required]
        [Column(TypeName = "money")]
        public decimal Price { get; set; }

        public ICollection<Image> Images { get; set; }
        public ICollection<Buyer> Buyers { get; set; }
        public List<Order> Orders { get; set; }
    }
}

OnlineShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Helpers;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Controllers
{
    public class CartController : Controller
    {
        private ShopDbContext _context;
        public CartController(ShopDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            if (ControllerContext.HttpContext.Session.Keys.Contains("cart"))
            {
                var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                ViewBag.cart = cart;
                ViewBag.totalPrice = cart.Sum(item => item.Product.Price * item.Quantity); 
            }
            
            return View();
        }

        public IActionResult Add(int id)
        {
            if (SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart") == null)
            {
                List<Item> cart = new();
                cart.Add(new Item { Product = _context.Products.Find(id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                int index = IsExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item { Product = _context.Products.Find(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            cart.RemoveAt(IsExist(id));
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

            return RedirectToAction("Index");
        }

        public IActionResult Order()
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");

            int buyerId = _context.Buyers.Where(b => b.Email == User.Identity.Name).Single().Id;

            foreach (var item in cart)
            {
                item.Product.Count -= item.Quantity;
                _context.Entry(item.Product).State = EntityState.Unchanged;

                Order order = new()
                {
                    BuyerFK = buyerId,
                    ProductFK = item.Product.Id,
                    Count = item.Quantity,
                    DateTime = DateTime.Now
                };

                _context.Orders.Add(order);
            }

            _context.SaveChanges();

            HttpContext.Session.Clear();

            return View();
        }

        private int IsExist(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }

            return -1;
        }
    }
}

OnlineShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        private ShopDbContext _context;
        private readonly ILogger<HomeController> _logger;
        public string SearchText { get; set; }

        public HomeController(ShopDbContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Products
                              .Include(p => p.Manufacturer)
                              .Include(p => p.Category)
                              .Include(p => p.Images)
                              .ToListAsync());
        }

        public async Task<IActionResult> Category(string category)
        {
            return View(await _context.Products
                              .Include(p => p.Category)
                              .Include(p => p.Images)
                              .Include(p => p.Manufacturer)
                              .Where(p => p.Category.Name == category)
                              .ToListAsync());
        }

        public async Task<IActionResult> Search(string text)
        {
            text = text.ToLower();

            return View(await _context.Products
                              .Include(p => p.Category)
                              .Include(p => p.Images)
                              .Include(p => p.Manufacturer)
                              .Where(p => p.Name.ToLower().Contains(text))
                              .ToListAsync());
        }

        public IActionResult Product(int id)
        {
            return View( _context.Products
                                  .Where(p => p.Id == id)
                                  .Include(p => p.Category)
                                  .Include(p => p.Images)
                                  .Include(p => p.Manufacturer)
                                  .Single()
                              );
        }

        public IActionResult Contacts()
        {
            return View();
        }
        public IActionResult Delivery()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineShop/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1>About</h1>

OnlineShop/Views/Home/Category.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = $"{ Model.First().Category.Name }";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bodyProducts">
    @foreach (var p in Model)
    {
        <div class="article">
            <p><b>@p.Manufacturer.Name</b></p>
            <a asp-controller="Home" asp-action="Product" asp-route-id="@p.Id">
                @if (p.Category.Name == "Laptops and computers")
                {
                    <img src="@p.Images.FirstOrDefault().Url" width="170" />
                }
                else
                {
                    <img src="@p.Images.FirstOrDefault().Url" height="200" />
                }
            </a>
            <p>@p.Name</p>
            <hr />
            <div>
                <p class="priceP"><b>@p.Price.ToString("0") ₴</b></p>
                <a class="linkBtn" asp-action="Add" asp-controller="Cart" asp-route-id="@p.Id">Add <b>to Cart</b></a>
            </div>
        </div>
    }
</div>

OnlineShop/Views/Home/Contacts.cshtml
@{
    ViewData["Title"] = "Contacts";
}

<h1>Contacts</h1>

OnlineShop/Views/Home/Delivery.cshtml
@{
    ViewData["Title"] = "Delivery";
}

<h1>Delivery</h1>

OnlineShop/Views/Home/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="imgDiv">
    <p>My online shop</p>
</div>
<div id="brandsDiv">
    <p> See Our <span>Brands</span></p>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed error delectus, illo incidunt voluptatem accusantium perspiciatis.</p>
</div>
<div id="homeBody">    
    <aside>
        <p>Categories</p>
        <ul>
            <li>
                <a asp-area="" asp-controller="Home" asp-action="Category" asp-route-category="Laptops and computers"><span>+</span> Laptops and computers</a>
            </li>
            <li>
                <a asp-area="" asp-controller="Home" asp-action="Category" asp-route-category="Smartphones"><span>+</span> Smartphones</a>
            </li>
            <li><span>+</span> TV</li>
            <li><span>+</span> Electronics</li>
        </ul>
    </aside>
    <div class="main">
        @foreach (var p in Model)
        {
        <div class="article">
            <p><b>@p.Manufacturer.Name</b></p>
            <a asp-controller="Home" asp-action="Product" asp-route-id="@p.Id">
                @if (p.Category.Name == "Laptops and computers")
                {
                    <img src="@p.Images.FirstOrDefault().Url" width="170"/>
                }
                else
                {
                    <img src="@p.Images.FirstOrDefault().Url" height="200"/>
                }
            </a>
            <p>@p.Name</p>
            <hr />
            <div>
                <p class="priceP"><b>@p.Price.ToString("0") ₴</b></p>
                <a class="linkBtn" asp-action="Add" asp-controller="Cart" asp-route-id="@p.Id">Add <b>to Cart</b></a>
            </div>
        </div>
        }
    </div>
</div>

OnlineShop/Views/Home/Product.cshtml
@model Product

@{
    ViewData["Title"] = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>@Model.Name</p>
<hr/>
<div class="bigProduct">
    <div class="gallery">
        @foreach (var i in Model.Images)
        {
            <a class="photo" href="@i.Url"><img src="@i.Url" width="150" height="100" /></a>
        }
    </div>
    <div class="info">
        <div>
            <p class="priceP"><b>@Model.Price.ToString("0") ₴</b></p>
            <a class="addCart" asp-action="Add" asp-controller="Cart" asp-route-id="@Model.Id">Add <b>to Cart</b></a>
        </div>
        <p>Color: @Model.Color</p>
        <p>@Model.Description</p>
    </div>
</div>

OnlineShop/Views/Home/Search.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "Search results";
}

<h2>Results</h2>
<hr />

<div class="bodyProducts">
    @foreach (var p in Model)
    {
        <div class="article">
            <p><b>@p.Manufacturer.Name</b></p>
            <a asp-controller="Home" asp-action="Product" asp-route-id="@p.Id">
                @if (p.Category.Name == "Laptops and computers")
                {
                    <img src="@p.Images.FirstOrDefault().Url" width="170" />
                }
                else
                {
                    <img src="@p.Images.FirstOrDefault().Url" height="200" />
                }
            </a>
            <p>@p.Name</p>
            <hr />
            <div>
                <p class="priceP"><b>@p.Price.ToString("0") ₴</b></p>
                <a class="linkBtn" asp-action="Add" asp-controller="Cart" asp-route-id="@p.Id">Add <b>to Cart</b></a>
            </div>
        </div>
    }
</div>